POST http://localhost:7071/api/HttpTriggerFunction
Content-Type: application/json

{
  "presenterName": "Marc Duiker",
  "sessionName": "Azure Functions Workshop",
  "attendeeName": "Someone else",
  "sessionScore": 4
}